import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCRTJjifN
Q/Q40Bh0zvgEXfAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIEFiOe3U9bDFDmVk
JadfFztYyFGA94HKP2cPZGYDPh/tAAAAkGzuo2xw2qSiGZmJekDQPZRJdhRfjKTn5Wznht
l7h7pErw0FwVkKJHuX56TwZ0Nuy7o7cMijQUFf2OcnXz3Ks5sHSH1m10MzN1h0i2yGrUfL
vy33V4BdRqtkT6ItPndE5wWHuMdWwY4SZc1y4OxgLBnNgN4Z0W4/ZdqqVOwAEi/DRx1Z+3
HlRs/LxzxRswaXfw==
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
