import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABBvwpaBlv
OvgTKKtDvCosUFAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIMNzwLUtiBhJqENg
xuTI2NnlJ479P5aq+mOvczNTu3I7AAAAkJR0xD1CkHS9WSu/S+wflR9OUD5BTHtNbHBDDJ
rdgW6ul141OQ5wVrVaS4KPCrQpmbSBvT7k0ouQfUY1o/9ZJQ0QxrFKOuBB/rFxU6DsSIVU
ulHF2GwrfDe+9fxkRUQf7ybVBRVuYAKr/1DnES5CftL5ir+2Fc4uQTTVE5BE+yHw6VX2om
YHn0mtt2+v87SGOg==
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
